**DS_Assignment_3**

Name : Gayatri Rajendra Jagadale

Seat No : 2337064

Batch : D

Lab : Software laboratory(II)

**Descriptive Statistics - Measures of Central Tendency and variability**

1)Provide summary statistics (mean, median, minimum, maximum, standard deviation) for a dataset (age, income etc.) with numeric variables grouped by one of the qualitative
(categorical) variable. For example, if your categorical variable is age groups and quantitative
variable is income, then provide summary statistics of income grouped by the age groups.
Create a list that contains a numeric value for each response to the categorical variable

In [77]:
import numpy as np
import pandas as pd

In [78]:
df = pd.read_csv('/adult_for_Assi_(A).csv')

In [79]:
df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K

In [80]:
df.shape

(48842, 15)

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48842 entries, 0 to 48841
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              48842 non-null  int64
 1   workclass        48842 non-null  object
 2   fnlwgt           48842 non-null  int64
 3   education        48842 non-null  object
 4   educational-num  48842 non-null  int64
 5   marital-status   48842 non-null  object
 6   occupation       48842 non-null  object
 7   relationship     48842 non-null  object
 8   race             48842 non-null  object
 9   gender           48842 non-null  object
 10  capital-gain     48842 non-null  int64
 11  capital-loss     48842 non-null  int64
 12  hours-per-week   48842 non-null  int64
 13  native-country   48842 non-null  object
 14  income           48842 non-null  object
dtypes: int64(6), object(9)
memory usage: 5.6+ MB

In [82]:
df.describe() #(include = 'all')

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week
count,48842.000000,4.884200e+04,48842.000000,48842.000000,48842.000000,48842.000000
mean,38.643585,1.896641e+05,10.078089,1079.067626,87.502314,40.422382
std,13.710510,1.056040e+05,2.570973,7452.019058,403.004552,12.391444
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.175505e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.781445e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.376420e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,4356.000000,99.000000

In [83]:
df.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [84]:
df.ndim

2

In [85]:
df = df.replace("NaN", np.nan)
df

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [86]:
df.isnull().sum()

age                0
workclass          0
fnlwgt             0
education          0
educational-num    0
marital-status     0
occupation         0
relationship       0
race               0
gender             0
capital-gain       0
capital-loss       0
hours-per-week     0
native-country     0
income             0
dtype: int64

In [87]:
df['age'].mean()

38.64358543876172

In [88]:
df['age'].median()

37.0

In [89]:
df['age'].mode()

0    36
Name: age, dtype: int64

In [90]:
df['age'].min()

17

In [91]:
df['age'].max()

90

In [92]:
df['age'].std()

13.710509934443557

In [93]:
df['income']= df['income'].replace(['<=50K','>50K'],[1,0])
df.head()

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,1
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,1
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,0
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,0
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,1

In [94]:
df.describe()

,age,fnlwgt,educational-num,capital-gain,capital-loss,hours-per-week,income
count,48842.000000,4.884200e+04,48842.000000,48842.000000,48842.000000,48842.000000,48842.000000
mean,38.643585,1.896641e+05,10.078089,1079.067626,87.502314,40.422382,0.760718
std,13.710510,1.056040e+05,2.570973,7452.019058,403.004552,12.391444,0.426649
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000,0.000000
25%,28.000000,1.175505e+05,9.000000,0.000000,0.000000,40.000000,1.000000
50%,37.000000,1.781445e+05,10.000000,0.000000,0.000000,40.000000,1.000000
75%,48.000000,2.376420e+05,12.000000,0.000000,0.000000,45.000000,1.000000
max,90.000000,1.490400e+06,16.000000,99999.000000,4356.000000,99.000000,1.000000

In [95]:
df['income']

0        1
1        1
2        0
3        0
4        1
        ..
48837    1
48838    0
48839    1
48840    1
48841    0
Name: income, Length: 48842, dtype: int64

In [96]:
df['income'].describe()

count    48842.000000
mean         0.760718
std          0.426649
min          0.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          1.000000
Name: income, dtype: float64

In [97]:
df['income'].mean()

0.7607182343065395

In [98]:
df['income'].std()

0.4266494219026857

In [99]:
df['income'].max()

1

In [100]:
df['income'].min()

0

In [101]:
df['income'].median()

1.0

In [102]:
df['income'].count()

48842

In [103]:
df1 = df.copy()

In [104]:
df1['income'] = df1['income'].replace([1,0], ['<=50K','>50K'])
df1

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
48838,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
48839,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
48840,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
48841,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [105]:
df1.groupby(["income","age"]).mean()

<ipython-input-105-37569cd1ff24>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df1.groupby(["income","age"]).mean()

                   fnlwgt  educational-num  capital-gain  capital-loss  \
income age
<=50K  17   179157.852101         6.685714     81.245378     33.302521
       18   193421.075406         8.220418     76.163573     37.852668
       19   204866.963810         9.091429     99.438095     42.700952
       20   197962.343525         9.342626     66.997302     35.776079
       21   199808.269725         9.424771     71.880734     41.124771
...                   ...              ...           ...           ...
>50K   83   196666.500000         9.500000  10025.500000   1196.000000
       84   172907.000000        10.000000      0.000000      0.000000
       85   155981.000000        13.000000      0.000000      0.000000
       88   263569.000000         7.000000   6418.000000      0.000000
       90   160300.076923        12.153846   7438.461538    140.384615

            hours-per-week
income age
<=50K  17        21.137815
       18        25.745940
       19        30.533333
       20        32.429856
       21        34.194495
...                    ...
>50K   83        52.500000
       84        35.000000
       85        40.000000
       88        40.000000
       90        45.153846

[142 rows x 5 columns]

In [106]:
df1.groupby(["income","age"]).median()

<ipython-input-106-0bad38c9fa26>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.median is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df1.groupby(["income","age"]).median()

              fnlwgt  educational-num  capital-gain  capital-loss  \
income age
<=50K  17   167658.0              7.0           0.0           0.0
       18   177613.0              9.0           0.0           0.0
       19   192307.5              9.0           0.0           0.0
       20   190281.5             10.0           0.0           0.0
       21   190057.5             10.0           0.0           0.0
...              ...              ...           ...           ...
>50K   83   196666.5              9.5       10025.5        1196.0
       84   172907.0             10.0           0.0           0.0
       85   155981.0             13.0           0.0           0.0
       88   263569.0              7.0        6418.0           0.0
       90   175491.0             13.0        6097.0           0.0

            hours-per-week
income age
<=50K  17             20.0
       18             24.0
       19             30.0
       20             35.0
       21             40.0
...                    ...
>50K   83             52.5
       84             35.0
       85             40.0
       88             40.0
       90             45.0

[142 rows x 5 columns]

In [107]:
df1.groupby(["income","age"]).std()

<ipython-input-107-8fd99583c5e6>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.std is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df1.groupby(["income","age"]).std()

                   fnlwgt  educational-num  capital-gain  capital-loss  \
income age
<=50K  17   101243.296009         0.957188   1407.535432    232.467309
       18   112046.448155         1.437882   1194.025643    245.870731
       19   116351.515261         1.394263   1515.336478    269.259342
       20   105724.045468         1.314072   1070.613636    250.178117
       21   107995.818286         1.476579    477.993196    271.679717
...                   ...              ...           ...           ...
>50K   83    61494.955439         4.949747  14178.198070   1691.399421
       84             NaN              NaN           NaN           NaN
       85             NaN              NaN           NaN           NaN
       88             NaN              NaN           NaN           NaN
       90    78487.937923         2.375084   8349.509253    506.163929

            hours-per-week
income age
<=50K  17        10.052279
       18        11.599559
       19        11.961223
       20        11.591010
       21        11.649644
...                    ...
>50K   83         3.535534
       84              NaN
       85              NaN
       88              NaN
       90        13.082088

[142 rows x 5 columns]

In [108]:
df1.groupby(["income","age"]).max()

                   workclass   fnlwgt     education  educational-num  \
income age
<=50K  17          State-gov   806316  Some-college               10
       18          State-gov   761006  Some-college               14
       19        Without-pay  1047822  Some-college               13
       20          State-gov   745817  Some-college               14
       21        Without-pay   811615  Some-college               14
...                      ...      ...           ...              ...
>50K   83       Self-emp-inc   240150     Bachelors               13
       84       Self-emp-inc   172907  Some-college               10
       85       Self-emp-inc   155981     Bachelors               13
       88   Self-emp-not-inc   263569          11th                7
       90   Self-emp-not-inc   313986   Prof-school               15

                marital-status        occupation   relationship   race gender  \
income age
<=50K  17              Widowed  Transport-moving      Unmarried  White   Male
       18              Widowed  Transport-moving           Wife  White   Male
       19            Separated  Transport-moving           Wife  White   Male
       20            Separated  Transport-moving           Wife  White   Male
       21              Widowed  Transport-moving           Wife  White   Male
...                        ...               ...            ...    ...    ...
>50K   83   Married-civ-spouse   Farming-fishing        Husband  White   Male
       84   Married-civ-spouse             Sales        Husband  White   Male
       85              Widowed   Exec-managerial  Not-in-family  White   Male
       88   Married-civ-spouse   Farming-fishing        Husband  White   Male
       90        Never-married             Sales           Wife  White   Male

            capital-gain  capital-loss  hours-per-week native-country
income age
<=50K  17          34095          1721              50  United-States
       18          34095          1721              72  United-States
       19          34095          2129              99     Yugoslavia
       20          34095          2258              84     Yugoslavia
       21           4865          2603              98        Vietnam
...                  ...           ...             ...            ...
>50K   83          20051          2392              55  United-States
       84              0             0              35  United-States
       85              0             0              40  United-States
       88           6418             0              40  United-States
       90          20051          1825              72  United-States

[142 rows x 13 columns]

In [109]:
df1.groupby(["income","age"]).min()

                   workclass  fnlwgt     education  educational-num  \
income age
<=50K  17                  ?   19752          10th                3
       18                  ?   20057          10th                3
       19                  ?   20469          10th                1
       20                  ?   19410          10th                1
       21                  ?   20728          10th                1
...                      ...     ...           ...              ...
>50K   83       Self-emp-inc  153183          10th                6
       84       Self-emp-inc  172907  Some-college               10
       85       Self-emp-inc  155981     Bachelors               13
       88   Self-emp-not-inc  263569          11th                7
       90                  ?   46786    Assoc-acdm                9

                marital-status       occupation   relationship  \
income age
<=50K  17   Married-civ-spouse                ?        Husband
       18             Divorced                ?        Husband
       19             Divorced                ?        Husband
       20             Divorced                ?        Husband
       21             Divorced                ?        Husband
...                        ...              ...            ...
>50K   83   Married-civ-spouse  Exec-managerial        Husband
       84   Married-civ-spouse            Sales        Husband
       85              Widowed  Exec-managerial  Not-in-family
       88   Married-civ-spouse  Farming-fishing        Husband
       90   Married-civ-spouse                ?        Husband

                          race  gender  capital-gain  capital-loss  \
income age
<=50K  17   Amer-Indian-Eskimo  Female             0             0
       18   Amer-Indian-Eskimo  Female             0             0
       19   Amer-Indian-Eskimo  Female             0             0
       20   Amer-Indian-Eskimo  Female             0             0
       21   Amer-Indian-Eskimo  Female             0             0
...                        ...     ...           ...           ...
>50K   83                White    Male             0             0
       84                White    Male             0             0
       85                White    Male             0             0
       88                White    Male          6418             0
       90                Black  Female             0             0

            hours-per-week native-country
income age
<=50K  17                4              ?
       18                2              ?
       19                2              ?
       20                2              ?
       21                1              ?
...                    ...            ...
>50K   83               50  United-States
       84               35  United-States
       85               40  United-States
       88               40  United-States
       90               15        Ecuador

[142 rows x 13 columns]

In [110]:
df1.groupby(["income","age"]).describe()

            fnlwgt                                                     \
             count           mean            std       min        25%
income age
<=50K  17    595.0  179157.852101  101243.296009   19752.0  111462.50
       18    862.0  193421.075406  112046.448155   20057.0  115815.00
       19   1050.0  204866.963810  116351.515261   20469.0  124527.25
       20   1112.0  197962.343525  105724.045468   19410.0  122023.50
       21   1090.0  199808.269725  107995.818286   20728.0  126938.25
...            ...            ...            ...       ...        ...
>50K   83      2.0  196666.500000   61494.955439  153183.0  174924.75
       84      1.0  172907.000000            NaN  172907.0  172907.00
       85      1.0  155981.000000            NaN  155981.0  155981.00
       88      1.0  263569.000000            NaN  263569.0  263569.00
       90     13.0  160300.076923   78487.937923   46786.0   88991.00

                                           educational-num             ...  \
                 50%        75%        max           count       mean  ...
income age                                                             ...
<=50K  17   167658.0  228313.00   806316.0           595.0   6.685714  ...
       18   177613.0  252756.25   761006.0           862.0   8.220418  ...
       19   192307.5  264492.75  1047822.0          1050.0   9.091429  ...
       20   190281.5  251375.50   745817.0          1112.0   9.342626  ...
       21   190057.5  250027.50   811615.0          1090.0   9.424771  ...
...              ...        ...        ...             ...        ...  ...
>50K   83   196666.5  218408.25   240150.0             2.0   9.500000  ...
       84   172907.0  172907.00   172907.0             1.0  10.000000  ...
       85   155981.0  155981.00   155981.0             1.0  13.000000  ...
       88   263569.0  263569.00   263569.0             1.0   7.000000  ...
       90   175491.0  206667.00   313986.0            13.0  12.153846  ...

           capital-loss         hours-per-week                              \
                    75%     max          count       mean        std   min
income age
<=50K  17           0.0  1721.0          595.0  21.137815  10.052279   4.0
       18           0.0  1721.0          862.0  25.745940  11.599559   2.0
       19           0.0  2129.0         1050.0  30.533333  11.961223   2.0
       20           0.0  2258.0         1112.0  32.429856  11.591010   2.0
       21           0.0  2603.0         1090.0  34.194495  11.649644   1.0
...                 ...     ...            ...        ...        ...   ...
>50K   83        1794.0  2392.0            2.0  52.500000   3.535534  50.0
       84           0.0     0.0            1.0  35.000000        NaN  35.0
       85           0.0     0.0            1.0  40.000000        NaN  40.0
       88           0.0     0.0            1.0  40.000000        NaN  40.0
       90           0.0  1825.0           13.0  45.153846  13.082088  15.0


              25%   50%    75%   max
income age
<=50K  17   15.00  20.0  25.00  50.0
       18   17.25  24.0  35.00  72.0
       19   20.00  30.0  40.00  99.0
       20   24.00  35.0  40.00  84.0
       21   25.00  40.0  40.00  98.0
...           ...   ...    ...   ...
>50K   83   51.25  52.5  53.75  55.0
       84   35.00  35.0  35.00  35.0
       85   40.00  40.0  40.00  40.0
       88   40.00  40.0  40.00  40.0
       90   40.00  45.0  50.00  72.0

[142 rows x 40 columns]

2. Write a Python program to display some basic statistical details like percentile, mean,
standard deviation etc. of the species of ‘Iris-setosa’, ‘Iris-versicolor’ and ‘Iris-versicolor’ of
iris.csv dataset.

In [111]:
ab = pd.read_csv('/Iris_for_Assi_(B).csv')

In [112]:
ab

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [113]:
ab.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [114]:
ab.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [115]:
ab.shape

(150, 6)

In [116]:
ab.describe(include ='all')

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
count,150.000000,150.000000,150.000000,150.000000,150.000000,150
unique,NaN,NaN,NaN,NaN,NaN,3
top,NaN,NaN,NaN,NaN,NaN,Iris-setosa
freq,NaN,NaN,NaN,NaN,NaN,50
mean,75.500000,5.843333,3.054000,3.758667,1.198667,NaN
std,43.445368,0.828066,0.433594,1.764420,0.763161,NaN
min,1.000000,4.300000,2.000000,1.000000,0.100000,NaN
25%,38.250000,5.100000,2.800000,1.600000,0.300000,NaN
50%,75.500000,5.800000,3.000000,4.350000,1.300000,NaN
75%,112.750000,6.400000,3.300000,5.100000,1.800000,NaN
max,150.000000,7.900000,4.400000,6.900000,2.500000,NaN

In [117]:
ab.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [118]:
ab.ndim

2

In [119]:
setosa = ab['Species'] == 'Iris-setosa'
print(ab[setosa].describe())
print('\nIris-versicolor')
setosa = ab['Species'] == 'Iris-versicolor'
print(ab[setosa].describe())
print('\nIris-virginica')
setosa = ab['Species'] == 'Iris-virginica'
print(ab[setosa].describe())

             Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  50.00000       50.00000     50.000000      50.000000      50.00000
mean   25.50000        5.00600      3.418000       1.464000       0.24400
std    14.57738        0.35249      0.381024       0.173511       0.10721
min     1.00000        4.30000      2.300000       1.000000       0.10000
25%    13.25000        4.80000      3.125000       1.400000       0.20000
50%    25.50000        5.00000      3.400000       1.500000       0.20000
75%    37.75000        5.20000      3.675000       1.575000       0.30000
max    50.00000        5.80000      4.400000       1.900000       0.60000

Iris-versicolor
              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000      50.000000     50.000000      50.000000     50.000000
mean    75.50000       5.936000      2.770000       4.260000      1.326000
std     14.57738       0.516171      0.313798       0.469911      0.197753
min     51.00000       4.900000      2.000000       3.000000      1.000000
25%     63.25000       5.600000      2.525000       4.000000      1.200000
50%     75.50000       5.900000      2.800000       4.350000      1.300000
75%     87.75000       6.300000      3.000000       4.600000      1.500000
max    100.00000       7.000000      3.400000       5.100000      1.800000

Iris-virginica
              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000       50.00000     50.000000      50.000000      50.00000
mean   125.50000        6.58800      2.974000       5.552000       2.02600
std     14.57738        0.63588      0.322497       0.551895       0.27465
min    101.00000        4.90000      2.200000       4.500000       1.40000
25%    113.25000        6.22500      2.800000       5.100000       1.80000
50%    125.50000        6.50000      3.000000       5.550000       2.00000
75%    137.75000        6.90000      3.175000       5.875000       2.30000
max    150.00000        7.90000      3.800000       6.900000       2.50000

In [120]:
df1.quantile()

<ipython-input-120-647cfc48d7d9>:1: FutureWarning: The default value of numeric_only in DataFrame.quantile is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df1.quantile()

age                    37.0
fnlwgt             178144.5
educational-num        10.0
capital-gain            0.0
capital-loss            0.0
hours-per-week         40.0
Name: 0.5, dtype: float64

In [121]:
df1.groupby('Species').mean()

KeyError: 'Species'

In [ ]:
df1.groupby('Species').median()

In [ ]:
df1.groupby('Species').std()

In [ ]:
df1.groupby('Species').describe()

In [ ]:
df1.groupby('Species').quantile()

In [ ]:
df1.groupby('Species').min()

In [ ]:
df1.groupby('Species').max()

In [ ]:
df1.groupby('Species').count()